{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pixl",
    "module": "facesearch",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-support-api",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-gpu",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-vision-common",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "vision-common",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "org.opencv",
          "module": "opencv",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.mediapipe",
          "module": "tasks-vision",
          "version": {
            "requires": "0.10.26.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "facesearch-1.0.2.aar",
          "url": "facesearch-1.0.2.aar",
          "size": 7084469,
          "sha512": "ce1217bf4cd6a4bfff9da43be7affe18aefff02da1e23f0b56f6d3eea3fc1cf4205c29b71fc375d82025649eefa5619a3315e6503c418b924e36fc4b70c99fb1",
          "sha256": "2e18a556b2be92c595cce90ef0a1a524856bd28d4aa54984778512124b07789a",
          "sha1": "1463511fa184b1a108ba187fe2114c890266f09b",
          "md5": "0d7c22e66965ba4f6d1c4dae26116c49"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-support-api",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-gpu",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-vision-common",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "vision-common",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "org.opencv",
          "module": "opencv",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.mediapipe",
          "module": "tasks-vision",
          "version": {
            "requires": "0.10.26.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "facesearch-1.0.2.aar",
          "url": "facesearch-1.0.2.aar",
          "size": 7084469,
          "sha512": "ce1217bf4cd6a4bfff9da43be7affe18aefff02da1e23f0b56f6d3eea3fc1cf4205c29b71fc375d82025649eefa5619a3315e6503c418b924e36fc4b70c99fb1",
          "sha256": "2e18a556b2be92c595cce90ef0a1a524856bd28d4aa54984778512124b07789a",
          "sha1": "1463511fa184b1a108ba187fe2114c890266f09b",
          "md5": "0d7c22e66965ba4f6d1c4dae26116c49"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "facesearch-1.0.2-sources.jar",
          "url": "facesearch-1.0.2-sources.jar",
          "size": 103169,
          "sha512": "d62755c082de0fef2f0587b50927ea23e96a41a6cff2e8d34c96ac1747891002fd80985b38e2669cd371212a8d82f4f9aed89112a6bc0d5184d8387b571906e6",
          "sha256": "527ed57e533edcf3a1e924b154e374ea8e9a3e1df69ed3348e0d7d8ae7733e11",
          "sha1": "34abe833a00936b78337acda33c76cb93e0ea660",
          "md5": "0c8a88005d96f4eb027e17309b3e3955"
        }
      ]
    }
  ]
}
