{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pixl",
    "module": "facesearch",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-support-api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-gpu",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-gpu-api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-vision-common",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "vision-common",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "org.opencv",
          "module": "opencv",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.mediapipe",
          "module": "tasks-vision",
          "version": {
            "requires": "0.10.26.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "facesearch-1.0.4.aar",
          "url": "facesearch-1.0.4.aar",
          "size": 7086661,
          "sha512": "6f86588182f1890536d3401116a126d20be84fdc839faa782bed49f6b2e0045da7ebcf039fbf36f914eafc387f0d0e96ff7ee6cb37edb1690c0876ad2d55b3f7",
          "sha256": "55fef2685baa8161f0c981353f64889a95ff02a669d841b9962bfd0bada144ac",
          "sha1": "7b9fa2eeb458e9b984d2b65332e1a1ef8d667cf8",
          "md5": "1834d4b3bb1abed622996e5349d0aa24"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-support-api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-gpu",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-gpu-api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-vision-common",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "vision-common",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "org.opencv",
          "module": "opencv",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.mediapipe",
          "module": "tasks-vision",
          "version": {
            "requires": "0.10.26.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "facesearch-1.0.4.aar",
          "url": "facesearch-1.0.4.aar",
          "size": 7086661,
          "sha512": "6f86588182f1890536d3401116a126d20be84fdc839faa782bed49f6b2e0045da7ebcf039fbf36f914eafc387f0d0e96ff7ee6cb37edb1690c0876ad2d55b3f7",
          "sha256": "55fef2685baa8161f0c981353f64889a95ff02a669d841b9962bfd0bada144ac",
          "sha1": "7b9fa2eeb458e9b984d2b65332e1a1ef8d667cf8",
          "md5": "1834d4b3bb1abed622996e5349d0aa24"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "facesearch-1.0.4-sources.jar",
          "url": "facesearch-1.0.4-sources.jar",
          "size": 105465,
          "sha512": "e88bfda498f9f4af9886908055e6f4de5946aec3859e544b4a4541ff47a2a7a507a14e2a1a6cc0687481385f2c5b5ad041a2ca76acd82daa844c91348e57d8ef",
          "sha256": "15947ea485d84e345013cc660e503c273de978c0c013dd6c7bf696b3652f48dd",
          "sha1": "7c7b607ed2314a17b09657a4b983f209bb960bf7",
          "md5": "ec84740196a7c5137b5ce15295d6700e"
        }
      ]
    }
  ]
}
