{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pixl",
    "module": "facesearch",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-support-api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-gpu",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-gpu-api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-vision-common",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "vision-common",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "org.opencv",
          "module": "opencv",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.mediapipe",
          "module": "tasks-vision",
          "version": {
            "requires": "0.10.26.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "facesearch-1.0.5.aar",
          "url": "facesearch-1.0.5.aar",
          "size": 7089277,
          "sha512": "e153ccbf906c1dd65eca39b9f823fd8cb66b79930650aeff322d8277ecb982614fd8ea7b7aead1cc30872c2f496f527d6d09a0e8a08e858c8db98061e5332689",
          "sha256": "59499c9ba0211f6f8bd616db7da1b2234e0f6ce3127c4d0b25475ab33d0a3a11",
          "sha1": "44bba8a2cefb0a8fdcc6e8170ef1fb3d3d2dcacb",
          "md5": "29f02736c4430110f8810dfc49111a0f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-support-api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-gpu",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.ai.edge.litert",
          "module": "litert-gpu-api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-vision-common",
          "version": {
            "requires": "19.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "vision-common",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "org.opencv",
          "module": "opencv",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.mediapipe",
          "module": "tasks-vision",
          "version": {
            "requires": "0.10.26.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "facesearch-1.0.5.aar",
          "url": "facesearch-1.0.5.aar",
          "size": 7089277,
          "sha512": "e153ccbf906c1dd65eca39b9f823fd8cb66b79930650aeff322d8277ecb982614fd8ea7b7aead1cc30872c2f496f527d6d09a0e8a08e858c8db98061e5332689",
          "sha256": "59499c9ba0211f6f8bd616db7da1b2234e0f6ce3127c4d0b25475ab33d0a3a11",
          "sha1": "44bba8a2cefb0a8fdcc6e8170ef1fb3d3d2dcacb",
          "md5": "29f02736c4430110f8810dfc49111a0f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "facesearch-1.0.5-sources.jar",
          "url": "facesearch-1.0.5-sources.jar",
          "size": 105697,
          "sha512": "ce826743ffac6cd05ce73f3786fb583d00a80db5d61854cdc088b5546e537e994b2e48de9dccd056b32af3ff0cbcd2cd360a831b3602d9e712b4503515dda77b",
          "sha256": "fc53d150b3374462d9dfa67dca0c7be8625807ba2a8d16384660713d2c72569c",
          "sha1": "64179a359063d3ba9bb1474fb01589b37f5f24d0",
          "md5": "a6719f0b99271fb8407ec1e99081c133"
        }
      ]
    }
  ]
}
